name: Injective list - Deploy UI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  env:
    SKIP_DEPLOYMENTS: ${{ secrets.SKIP_DEPLOYMENTS }}

jobs:
  deploy:
    if: ${{ SKIP_DEPLOYMENTS != 'true' && (github.event_name == 'workflow_dispatch' || contains(github.event.commits[0].message, 'generate json files') && !contains(github.event.commits[0].message, 'skip deploy')) }}
    name: "Trigger deployments"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Sleep for 60s
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 60s

      - name: Deploy mito (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: mitoFinance/mito-ui
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy mito
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: mainnet.yml
          ref: master
          repo: mitoFinance/mito-ui
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy bridge (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-bridge
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy bridge (mainnet)
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/660d7b9ab0d0ef0b0f685131

      - name: Rebuild helix (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-helix
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild helix
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: mainnet.yml
          ref: master
          repo: injectiveLabs/injective-helix
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy explorer (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-explorer
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy explorer (testnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: testnet.yaml
          ref: master
          repo: injectiveLabs/injective-explorer
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy explorer
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: mainnet.yaml
          ref: master
          repo: injectiveLabs/injective-explorer
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild hub (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-hub
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild Hub
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: mainnet.yml
          ref: master
          repo: injectiveLabs/injective-hub
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy OLP (mainnet)
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6656effe7e59027d29160fd5

      - name: Deploy Admin UI (mainnet)
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/665708f5e5ef6799ac221b79
