name: Injective list - generate data

on:
  push:
    branches:
      - master

jobs:
  if: "!contains(github.event.commits[0].message, 'generate json files')"
  generate:
    name: "Regenerate JSON files"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: Install dependencies
        run: cd ts-scripts && yarn

      - name: Generate tokens
        uses: borales/actions-yarn@v4
        with:
          cmd: tokens:generate
          dir: "ts-scripts"

      - name: Generate market slugs
        uses: borales/actions-yarn@v4
        with:
          cmd: slugs:generate
          dir: "ts-scripts"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate json files"

  deploy:
    if: "!contains(github.event.commits[0].message, 'skip deploy') && !contains(github.event.commits[0].message, 'generate json files')"
    needs: generate
    name: "Trigger deployments"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Sleep for 60s
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 60s

      - name: Deploy mito (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: mitoFinance/mito-ui
          token: "${{ secrets.GH_TOKEN }}"

      - name: Deploy bridge (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-bridge
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild bridge
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/660d7b9ab0d0ef0b0f685131

      - name: Rebuild helix (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-helix
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild helix
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: mainnet.yml
          ref: master
          repo: injectiveLabs/injective-helix
          token: "${{ secrets.GH_TOKEN }}"
