name: Mito Devnet Deployments

on:
  push:
    branches:
      - master

jobs:
  master:
    name: "Regenerate JSON files"
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      ## Github Actions
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd ts-scripts && yarn

      - name: Generate market slugs
        uses: borales/actions-yarn@v4
        with:
          cmd: slugs:generate
          dir: "ts-scripts"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate json files"

      - name: Rebuild mito
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: mitoFinance/mito-ui
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild helix
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-helix
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild bridge (devnet)
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: devnet.yml
          ref: dev
          repo: injectiveLabs/injective-bridge
          token: "${{ secrets.GH_TOKEN }}"

      - name: Rebuild bridge (mainnet)
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/660d7b9ab0d0ef0b0f685131
